WEBSITE_NAME: "Operations Dashboard"
GRAFANA_BASE_URL: "https://grafana.example.com"
GRAFANA_DASHBOARD_URL_DEPLOYMENT: "/d/deployment-metrics"
GRAFANA_DASHBOARD_URL_NAMESPACE: "/d/namespace-metrics"
LABEL_SELECTOR: "app.kubernetes.io/name=my-app"
SIDEBAR_URLS:
  - name: "Production Metrics"
    url: "https://grafana.example.com/prod"
    icon: "chart"
    description: "Production environment metrics and dashboards"
  - name: "API Documentation"
    url: "https://api-docs.example.com"
    icon: "text"
    description: "API documentation and endpoints"
  - name: "Terminal Access"
    url: "https://terminal.example.com"
    icon: "terminal"
    description: "Web-based terminal access"
  - name: "External Tools"
    url: "https://tools.example.com"
    icon: "url"
    description: "Collection of external development tools"
SPECIAL_NAMESPACES:
  - "dev"